In [1]:
import pandas as pd

In [3]:
roll=pd.Series([1,2,3,4,5])
name=pd.Series(['sia','ravi','geet','ajeenkya','avinash'])
marks=pd.Series([85,67,50,40,90])

In [4]:
print(roll,name,marks)

0    1
1    2
2    3
3    4
4    5
dtype: int64 0         sia
1        ravi
2        geet
3    ajeenkya
4     avinash
dtype: object 0    85
1    67
2    50
3    40
4    90
dtype: int64

In [6]:
df=pd.DataFrame({
    'id':roll,
    'name':name,
    'marks':marks
})

In [7]:
df

   id      name  marks
0   1       sia     85
1   2      ravi     67
2   3      geet     50
3   4  ajeenkya     40
4   5   avinash     90

In [8]:
df.ndim

2

In [13]:
df.shape

(5, 3)

In [14]:
df.size

15

In [16]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [17]:
'''
url-->https://mitu.co.in/dataset-->will connect to driver folder

download all the datasets starting eith student *
put them into the same folder as ur current working directory
''';

In [1]:
pwd

'C:\\Users\\Lenovo'

In [4]:
import pandas as pd

In [9]:
df=pd.read_csv("student1.csv")

In [10]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [8]:
pwd

'C:\\Users\\Lenovo'

In [12]:
col=['roll','name','class','marks','age']

df=pd.read_csv("student1.csv",names=col)

In [13]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [14]:
#student3.tsv

In [17]:
df=pd.read_csv('student3.tsv',sep='\t')

In [18]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21