In [28]:
#Social_Network_Ads

In [29]:
import pandas as pd
import numpy as np

In [30]:
df=pd.read_csv('Social_Network_Ads.csv')

In [31]:
df

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [32]:
df.head()

    User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [33]:
df.shape

(400, 5)

In [34]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [35]:
newdf=df.copy()

In [36]:
newdf

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [37]:
#import the label encoder class
from sklearn.preprocessing import LabelEncoder

In [38]:
le=LabelEncoder()   # creating the class

In [39]:
newdf['Gender']=le.fit_transform(newdf['Gender'])

In [40]:
newdf

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510       1  19.0          19000.0          0
1    15810944       1  35.0          20000.0          0
2    15668575       0  26.0          43000.0          0
3    15603246       0  27.0          57000.0          0
4    15804002       1  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863       0  46.0          41000.0          1
396  15706071       1  51.0          23000.0          1
397  15654296       0  50.0          20000.0          1
398  15755018       1  36.0          33000.0          0
399  15594041       0  49.0          36000.0          1

[400 rows x 5 columns]

In [41]:
le.classes_

array(['Female', 'Male'], dtype=object)

In [42]:
# one hot encoding

In [43]:
df=pd.get_dummies(df)

In [44]:
df

      User ID   Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510  19.0          19000.0          0          False         True
1    15810944  35.0          20000.0          0          False         True
2    15668575  26.0          43000.0          0           True        False
3    15603246  27.0          57000.0          0           True        False
4    15804002  19.0          76000.0          0          False         True
..        ...   ...              ...        ...            ...          ...
395  15691863  46.0          41000.0          1           True        False
396  15706071  51.0          23000.0          1          False         True
397  15654296  50.0          20000.0          1           True        False
398  15755018  36.0          33000.0          0          False         True
399  15594041  49.0          36000.0          1           True        False

[400 rows x 6 columns]

In [45]:
import seaborn as sns

In [46]:
df=sns.load_dataset('taxis');

In [47]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [48]:
""""

load the taxis dataset from seaborn 
remove pickup and dropoff columns from the dataset
encode all the catrgorical column using lable encoding
ideally create a function which encode when u pass the dataframe 
""";

In [49]:
df=df.drop(['pickup','dropoff'],axis=1)

In [50]:
def encode_column(dataframe):
    df_encoded=dataframe.copy()
    le=LabelEncoder()



    for col in df_encoded.columns:
        if df_encoded[col].dtype=='object':
            df_encoded[col]=le.fit_transform(df_encoded[col])
    return df_encoded

In [51]:
df_encoded=encode_column(df)

In [52]:
print(df_encoded.head())

   passengers  distance  fare   tip  tolls  total  color  payment  \
0           1      1.60   7.0  2.15    0.0  12.95      1        1
1           1      0.79   5.0  0.00    0.0   9.30      1        0
2           1      1.37   7.5  2.36    0.0  14.16      1        1
3           1      7.70  27.0  6.15    0.0  36.95      1        1
4           3      2.16   9.0  1.10    0.0  13.40      1        1

   pickup_zone  dropoff_zone  pickup_borough  dropoff_borough
0           99           176               2                2
1          174           182               2                2
2            1           190               2                2
3           86           202               2                2
4          116           202               2                2

In [53]:
print(df_encoded.dtypes)

passengers           int64
distance           float64
fare               float64
tip                float64
tolls              float64
total              float64
color                int64
payment              int64
pickup_zone          int64
dropoff_zone         int64
pickup_borough       int64
dropoff_borough      int64
dtype: object